### ISSUE TITLE
"GPU readback error" on Android

### ISSUE THREAD

**Issue by ShacharWeis** [keijiro/AsyncCaptureTest#3]
This doesn't work on Android,

req.hasError is always true. Any ideas why or if it's fixable?

**Comment by keijiro** [comment]
Could you check if it's running on Vulkan? The async readback feature isn't supported on GLES.

**Comment by ShacharWeis** [comment]
Oh no. 
It would have been nice if the Unity documentation mentioned not supporting GLES :(
