### ISSUE TITLE
Make SaveBitmap async 

### ISSUE THREAD

**Issue by matteolobello** [keijiro/AsyncCaptureTest#4]
Hi!
Is it possible to make the SaveBitmap() method async? 
I need to encode the Color32/Byte array to JPG in another thread so that it doesn't create any micro-lag on the main thread.
Thanks a lot in advance!

**Comment by keijiro** [comment]
That's technically possible, that may be far more complicated than the current implementation though.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by matteolobello** [comment]
Thanks for your reply!

May I ask you what could be the right way to do it?
I’ve searched all over the internet and there is no such thing as “asynchronous raw texture data to JPG”. 😔

**Comment by keijiro** [comment]
You have to implement a jpeg encoder by yourself because the functionality provided with Unity is not thread safe in general.

**Comment by matteolobello** [comment]
May I ask you to send me some links that could help me understand how to encode a JPG from Raw Texture Data?

**Comment by keijiro** [comment]
I have no experience with implementing a jpeg encoder, so unfortunately, I couldn't give any detailed advice for you about it.
