### ISSUE TITLE
Crash after about 10 min

### ISSUE THREAD

**Issue by TuncayCakmak** [keijiro/AsyncCaptureTest#6]
Hi there,

i have tried this project with different Unity Versions (2019.4.14f1 , 2020.3.25f1 and 2021.2.8f1) and have a problem. Hope someone can help me. 

The application crashes after about 10 minutes. 

I have also tried the same test while deactivating this line "System.IO.File.WriteAllBytes("test.png", encoded.ToArray());"
It still crashed in editor or standalone mode after running for about 10 minutes.
I have tried the tool "Log Viewer" to see in Standalone Mode if there is a Memory Leak. Everything looked normal. Maybe there are better tools to analyse?

Is this a Unity Bug?

Is it maybe better to replace this "yield return new WaitForSeconds(1);" with something like a request done to have maximum speed? 

I would like to create a video stream application which is stable and fast. Is it wise to use AsyncGPUReadback or is there a better and more stable option? 

Thank you, hope you have some advises!

**Comment by keijiro** [comment]
Which platform are you using?

**Comment by TuncayCakmak** [comment]
Dear Keijiro,

i have tried it on 2 different PCs. One is Windows 10 Home (GTX 1080) and the other one is Windows 10 Pro (GTX 1160 Super).

Best

**Comment by keijiro** [comment]
Thanks for clarification.

How about adding `encoded.Dispose();` after [this line](https://github.com/keijiro/AsyncCaptureTest/blob/master/Assets/AsyncCapture.cs#L57)?

**Comment by TuncayCakmak** [comment]
Dear Keijiro,

it seems that "encoded.Dispose();" solves the issue, ill make additional tests. I have also realised that the energy management "turn off display after 10 min" can lead to other issues. Ill continue with tests and report here the results. 

I would kindly ask you, how can i use your script to reduce the 1 Second waiting time to a minimum? Do i need to integrate something like "request done" into the callback?

Best and thank you!

**Comment by keijiro** [comment]
> how can i use your script to reduce the 1 Second waiting time to a minimum?

Just remove the `yield return new WaitForSeconds(1);` line.

**Comment by TuncayCakmak** [comment]
Dear Keijiro,

if i remove "yield return new WaitForSeconds(1);" i get this error:

ERROR:
InvalidOperationException: The Unity.Collections.NativeArray'1[System.Byte] can no longer be accessed, since its owner has been invalidated. You can simply Dispose() the container and create a new one.

I tried instead of "yield return new WaitForSeconds(1);" this "yield return new WaitForSeconds(0.07f);"

I get the Error if a roughly go below "yield return new WaitForSeconds(0.07f);" , for example "yield return new WaitForSeconds(0.05f);"

Do you know why this happens?

Best

**Comment by TuncayCakmak** [comment]
I have also tried this:

using Unity.Collections;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.UI;
using System.Collections;

public class AsyncCapture : MonoBehaviour
{
   
    public RenderTexture rendtex;
    public ScreenShare screen;
    public bool ready=false;
   
    public byte[] imagebytes;
  

    (RenderTexture grab, RenderTexture flip) _rt;
    NativeArray<byte> _buffer;

    Vector2 scale = new Vector2(1, -1);
    Vector2 offs = new Vector2(0, 1);

    private void Start()
    {
     
        var (w, h) = (Screen.currentResolution.width, Screen.currentResolution.height);
    
        _rt.grab = new RenderTexture(w, h, 0);
        _rt.flip = new RenderTexture(w, h, 0);

        _buffer = new NativeArray<byte>(w * h * 4, Allocator.Persistent,
                                        NativeArrayOptions.UninitializedMemory);


        StartCoroutine(Astest());

        
    }

    IEnumerator Astest()
    {
        while (true)
        {
            

            yield return new WaitForEndOfFrame();


            //ScreenCapture.CaptureScreenshotIntoRenderTexture(_rt.grab);
            
            _rt.grab = rendtex;

            Debug.Log(_rt.grab.width);

            Graphics.Blit(_rt.grab, _rt.flip, scale, offs);

            AsyncGPUReadbackRequest request = AsyncGPUReadback.RequestIntoNativeArray(ref _buffer, _rt.flip, 0);
            yield return new WaitUntil(() => {
                if (request.done || request.hasError)
                {
                    if (request.hasError)
                    {
                        Debug.Log("GPU readback error detected.");
                        return true;
                    }

                   
                    var encoded = ImageConversion.EncodeNativeArrayToJPG
                     (_buffer, _rt.flip.graphicsFormat,
                      (uint)_rt.flip.width, (uint)_rt.flip.height);


                    if (!ready)
                    {
                        imagebytes = NativeArrayExtension.ToRawBytes(encoded);
                        encoded.Dispose();
                        
                        ready = true;
                    }

                    return true;
                }
                else
                {
                    return false;
                }
            });


        }

    }

    void OnDestroy()
    {
        AsyncGPUReadback.WaitAllRequests();

        Destroy(_rt.flip);
        Destroy(_rt.grab);

        _buffer.Dispose();
    }

    


}


Runs really fine but this is crashing after a few minutes....

Hope you have some ideas. Thank you for your time!

**Comment by TuncayCakmak** [comment]
Dear Keijiro,

i found now a solution by using this
AsyncGPUReadbackRequest request = AsyncGPUReadback.RequestIntoNativeArray(ref _buffer, _rt.flip, 0);
            yield return new WaitUntil(() => {

Thank you very much for your time. I think everything works now well.

Later on i will test again what happens if the Monitor turns off after 10 minutes (Energy management) and will report it as soon as i have the results. Thank you so much for your time and have a great day!

Best

**Comment by keijiro** [comment]
I fixed the memory leak in the latest commit.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
